### ISSUE TITLE
Error: Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by DANIELADIKO** [cuongdevjs/reactjs-social-login#10]
Hi ,
I encountered a problem when adding the package to my project. I use react 17.0.2 with typescript and when adding the button for the connection with Facebook, the project stops working when calling the connection page with the following message:  

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem

![Capture d’écran 2021-06-12 à 12 18 22](https://user-images.githubusercontent.com/26333778/121775616-55be9700-cb78-11eb-87b4-3527a9478824.png)

![Capture d’écran 2021-06-12 à 12 24 07](https://user-images.githubusercontent.com/26333778/121775782-2c523b00-cb79-11eb-8795-cb6568021f15.png)

At the line 52

![Capture d’écran 2021-06-12 à 12 24 31](https://user-images.githubusercontent.com/26333778/121775803-3d9b4780-cb79-11eb-813d-77e363bf0c95.png)

**Comment by cuongdevjs** [comment]
can you provide codesandbox? or you can update to new version?

**Comment by cuongdevjs** [comment]
https://codesandbox.io/s/lingering-moon-921z8?file=/src/App.tsx

**Comment by cuongdevjs** [comment]
you can see in my example.
