### ISSUE TITLE
Could not find a declaration file for module 'reactjs-social-login'. 

### ISSUE THREAD

**Issue by MariosPalazis** [cuongdevjs/reactjs-social-login#107]
Could not find a declaration file for module 'reactjs-social-login'. 'c:/Users/marios.palazis/Desktop/Social Satellite/frontend/node_modules/reactjs-social-login/dist/reactjs-social-login.modern.js' implicitly has an 'any' type.not find a declaration file for module 'reactjs-social-login'. 'c:/Users/marios.palazis/Desktop/Social Satellite/frontend/node_modules/reactjs-social-login/dist/reactjs-social-login.modern.js' implicitly has an 'any' type.

**Comment by cuongdevjs** [comment]
seem it is relevant to the typescript issue when installing this library. For this, this solution you can try with:
- add this line into any d.ts file:
`declare module 'reactjs-social-login'`:

**Comment by MariosPalazis** [comment]
Could not find a declaration file for module 'reactjs-social-login'. 'c:/Users/marios.palazis/Desktop/Social Satellite/frontend/node_modules/reactjs-social-login/dist/reactjs-social-login.modern.js' implicitly has an 'any' type.
  There are types at 'c:/Users/marios.palazis/Desktop/Social Satellite/frontend/node_modules/reactjs-social-login/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'reactjs-social-login' library may need to update its package.json or typings.
