### ISSUE TITLE
NOT ABLE TO GET EMAILS OF THE USER on resolve for LoginSocialLinkedin

### ISSUE THREAD

**Issue by udayan46** [cuongdevjs/reactjs-social-login#110]

**Comment by cuongdevjs** [comment]
pass `scope` props down to the `LoginSocialLinkedin` component, and then config the respective scope it on your LinkedIn app at https://www.linkedin.com/developers

**Comment by GuffyG** [comment]
Got same issue even after setting scope which is configured in LinkedIn App 

<img width="338" alt="Screenshot 2023-07-21 at 9 54 13 AM" src="https://github.com/cuongdevjs/reactjs-social-login/assets/140077245/ed80eb13-95d8-42f5-8f16-e1c4dd322321">
