### ISSUE TITLE
Hovering over Apple icon causes it to disappear 

### ISSUE THREAD

**Issue by Nebelung-Dev** [cuongdevjs/reactjs-social-login#113]
See this image.
![image](https://github.com/cuongdevjs/reactjs-social-login/assets/81875430/fb01ad78-7cf0-473e-bdd0-9580fcaef10f)

**Comment by cuongdevjs** [comment]
OH, it is relevant to CSS, but you still can click on it. In this library, the UI inside absolutely can be customized by yourself.

**Comment by cuongdevjs** [comment]
OH, it is relevant to CSS, but you still can click on it. In this library, the UI inside absolutely can be customized by yourself.

**Comment by cuongdevjs** [comment]
fixed
