### ISSUE TITLE
Helpers/constants Cannot find module

### ISSUE THREAD

**Issue by JoseArellanoV** [cuongdevjs/reactjs-social-login#114]
**Describe the bug**
When i run "npm run start" return an error:
 Cannot find module 'helper/constants' or its corresponding type declarations. for all social login who uses 'helper/constants'

LoginSocialLinkedin/index.tsx(7,31): semantic error TS2307: Cannot find module 'helper/constants' or its corresponding type declarations.

I'm gues maybe is a error when try to use typescript (rpt2 plugin)

**To Reproduce**
1. npm run start on /reactjs-social-login folder

**Expected behavior**

**Screenshots**
![image](https://github.com/cuongdevjs/reactjs-social-login/assets/121171928/f581c5d2-f78f-4874-88a0-0f969221953a)

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - nodeJS, 12.22.12

**Additional context**

**Comment by cuongdevjs** [comment]
please upgrade nodejs version > 14.xx.xx

**Comment by JoseArellanoV** [comment]
thanks for the answer...

> please upgrade nodejs version > 14.xx.xx

but doesn't matters...it give me the same issue

![image](https://github.com/cuongdevjs/reactjs-social-login/assets/121171928/5b88d734-d592-4102-a21f-d74a8fcf3a55)

**Comment by JoseArellanoV** [comment]
> have you reinstalled node_modules after upgrading nodejs?

yes, i remove the forder with rm -rf node_modules/

then npm install with node 14.x, i will clone again the repo to tested

**Comment by cuongdevjs** [comment]
oh, my fault. you need to create a new file inside src/helper folder named constants.ts

and content in this file

````
export const PASS_CORS_KEY = '';
````

you need to register this key at [this link](https://github.com/gridaco/cors.sh/issues/7)

**Comment by cuongdevjs** [comment]
No more information. Feel free to tell me or open a new issue if you have any questions.

**Comment by wlfaltera** [comment]
this should be in the docs
