### ISSUE TITLE
TypeError: Failed to fetch console error for LoginSocialFacebook

### ISSUE THREAD

**Issue by drattansingh** [cuongdevjs/reactjs-social-login#115]
**Describe the bug**
When I use LoginSocialFacebook, it is working and retrieving the Facebook data/provider but is also printing to console a TypeError: Failed to fetch error (see  [error_console_link](https://i.stack.imgur.com/B0vHY.png)  ).  I tried using LoginSocialGoogle and it's working perfectly without any console errors so this error is specific to LoginSocialFacebook only 

```
import {LoginSocialFacebook, LoginSocialGoogle } from 'reactjs-social-login'
import {FacebookLoginButton, GoogleLoginButton } from 'react-social-login-buttons'

const handlerFacebookLogin = useCallback(() => {
	//console.log("login start");
}, []);

const handlerFacebookLogout = useCallback(() => {
	//console.log("logout success");
}, []);

return(
<LoginSocialFacebook
	appId={process.env.REACT_APP_FACEBOOK_APP_ID}
	fieldsProfile={ "id,first_name,last_name,middle_name,name,name_format,picture,short_name,email" }
	onLoginStart={handlerFacebookLogin}
	onLogoutSuccess={handlerFacebookLogout}
	redirect_uri={null}
	onResolve={({provider,data})=>{ 
		console.log(data) }}
	onReject={(err) => {
		console.log(err);
	}}
	>
	<FacebookLoginButton />
</LoginSocialFacebook>
);
```

**To Reproduce**
1. Go to https://codesandbox.io/s/intelligent-minsky-82ylzd?file=/src/
2. Click on Facebook button
3. Scroll down to console 
4. You'll see the facebook information as well as typeError in the console

**Expected behavior**
How to hide the console errors?

**Comment by cuongdevjs** [comment]
please try pass prop: `isOnlyGetToken` to provider

**Comment by drattansingh** [comment]
```
return(
<LoginSocialFacebook
	appId={process.env.REACT_APP_FACEBOOK_APP_ID}
	fieldsProfile={ "id,first_name,last_name,middle_name,name,name_format,picture,short_name,email" }
	onLoginStart={handlerFacebookLogin}
	onLogoutSuccess={handlerFacebookLogout}
	redirect_uri={null}
	onResolve={({provider,data})=>{ 
		console.log(data) }}
	onReject={(err) => {
		console.log(err);
	}}
        isOnlyGetToken={true}
	>
	<FacebookLoginButton />
</LoginSocialFacebook>
);
```
When I add `isOnlyGetToken `props as above, the `console.log(data)` isn't printing out the name and email, e.g.:

![image](https://github.com/cuongdevjs/reactjs-social-login/assets/96189286/f198a7f6-6e7f-4e65-9069-d5c5f766ab1e)

**Comment by cuongdevjs** [comment]
name and email should be fetched on backend, not client-side.
