### ISSUE TITLE
error in component LoginSocialTwitter props redirect_uri

### ISSUE THREAD

**Issue by mariosergioalberto** [cuongdevjs/reactjs-social-login#116]
Hello 

I have a problem with the LoginSocialTwitter component in the props redirect_uri.
Copy the code from your example where you define constant
REDIRECT_URI=http://localhost:3000

<LoginSocialTwitter
            isOnlyGetToken
            client_id={process.env.REACT_APP_TWITTER_V2_APP_KEY || ''}
            **redirect_uri={REDIRECT_URI}**
            onLoginStart={onLoginStart}
            onResolve={({ provider, data }) => {
              setProvider(provider)
              setProfile(data)
            }}
            onReject={(err) => {
              console.log(err)
            }}
          >
            <TwitterLoginButton />
          </LoginSocialTwitter>

**Screenshots**
![image](https://github.com/cuongdevjs/reactjs-social-login/assets/38430418/c4b7523d-bf23-4492-850b-3398e026bcb6)

I press the Authorize app button, the window does not close, but loads the home in this same window.

![image](https://github.com/cuongdevjs/reactjs-social-login/assets/38430418/1f810b0e-62c8-42c9-a6bc-b612285e9f3d)

Also I tried with REDIRECT_URI=window.location.href but the twitter application not working

![image](https://github.com/cuongdevjs/reactjs-social-login/assets/38430418/13485b1c-1245-4e3b-a75c-5dbb22f09232)

**Desktop**
 - OS:  Windows
 - Browser: Chrome, Edge

**Comment by cuongdevjs** [comment]
Please use REDIRECT_URI = window.location.href instead

**Comment by mariosergioalberto** [comment]
Sorry.
I used REDIRECT_URI = window.location.href but twitter application not working like you can see in the last image. I don't know what the problem.

**Comment by cuongdevjs** [comment]
you need config your app correctly first.
