### ISSUE TITLE
Login with GitHub and LinkedIn doesn't work

### ISSUE THREAD

**Issue by amityahav90** [cuongdevjs/reactjs-social-login#119]
**Describe the bug**
When trying to login with GitHub and LinkedIn, I cannot get the returned `data` and `provider`.
The `github` property remains in the local storage and no error is sent to the `onReject` callback.

**To Reproduce**
1. Click on login with GitHub
2. Fill in the details and click on "Login"
3. The `code` property is added to the local storage

**Expected behavior**
The `data` and `provider` should return in the `onResolve` callback.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac 13.4.1
 - Browser Chrome 114.0.5735.198

**Comment by cuongdevjs** [comment]
Please reproduce your problem by code.
