### ISSUE TITLE
When using the GitHub social login, the "instagram" property is deleted from local storage

### ISSUE THREAD

**Issue by amityahav90** [cuongdevjs/reactjs-social-login#120]
**Describe the bug**
When using the GitHub social login, the "instagram" property is deleted from local storage instead of the "github" property.

**Expected behavior**
The "github" property should be deleted

**Screenshots**
![image](https://github.com/cuongdevjs/reactjs-social-login/assets/33030590/e0b6da06-df4a-4213-a0b7-f8df3ae1c980)

**Comment by cuongdevjs** [comment]
This issue has been fixed in version 2.6.3
Thank you so much.
