### ISSUE TITLE
Email field not returned while using Linkedin login

### ISSUE THREAD

**Issue by GuffyG** [cuongdevjs/reactjs-social-login#121]
Here is the sample response:
{
    "access_token": "XXXX",
    "expires_in": 5183999,
    "scope": "r_emailaddress,r_liteprofile",
    "localizedLastName": "XXX",
    "profilePicture": {
       
            },
            
    "firstName": {
        "localized": {
            "en_US": "XXX"
        },
        "preferredLocale": {
            "country": "US",
            "language": "en"
        }
    },
    "lastName": {
        "localized": {
            "en_US": "XXX"
        },
        "preferredLocale": {
            "country": "US",
            "language": "en"
        }
    },
    "id": "XXXXX",
    "localizedFirstName": "XXX"
}

**Comment by GuffyG** [comment]
@cuongdevjs  can you please look into it

**Comment by GuffyG** [comment]
<img width="338" alt="Screenshot 2023-07-21 at 9 54 13 AM" src="https://github.com/cuongdevjs/reactjs-social-login/assets/140077245/f236503c-11ea-41ed-8b5c-f0f4a084d031">

**Comment by GuffyG** [comment]
@cuongdevjs can you please help me out

**Comment by cuongdevjs** [comment]
Please try to pass props `scope="r_emailaddress, r_liteprofile"` and ensure your app has been configured correctly.
<img width="868" alt="CleanShot 2023-08-09 at 06 46 31@2x" src="https://github.com/cuongdevjs/reactjs-social-login/assets/33604446/a6ad02d1-5d96-4679-8256-39d6dcf63381">

**Comment by GuffyG** [comment]
> Please try to pass props `scope="r_emailaddress, r_liteprofile"` and ensure your app has been configured correctly.
> <img alt="CleanShot 2023-08-09 at 06 46 31@2x" width="868" src="https://user-images.githubusercontent.com/33604446/259320075-a6ad02d1-5d96-4679-8256-39d6dcf63381.png">

Thanks for the response,
Well, the scope is defined and also configured in the LinkedIn app. Also, this is an app used for ios app too and there I am able to get the email after login. this means the app is configured properly.

Here is the react code :

<LoginSocialLinkedin
                  className="btn btn-linkedin"
                  client_id={process.env.REACT_APP_LN_APP_ID || ""}
                  client_secret={process.env.REACT_APP_LN_SECRET || ""}
                  redirect_uri={`${window.location.origin}/login`}
                  scope="r_liteprofile r_emailaddress w_member_social"
                  onResolve={(response) => {
                    linkedInResponseOnLogin(response);
                  }}
                  onReject={() => {}}
                ></LoginSocialLinkedin>
                
 I really appreciate any help you can provide.

**Comment by cuongdevjs** [comment]
each scope need to separate by comma

**Comment by Lkl9ik14011** [comment]
Maybe not the best way
in onResolve you can get rest api
this work for me!

` 
        onResolve={async ({ provider, data }) => {
            await handleResolve(provider, data);
         }} `
 `
 
 `
 const handleResolve = async (provider, response) => {
      const userEmail = await fetch(
         `https://api.linkedin.com/v2/emailAddress?q=members&projection=(elements*(handle~))&oauth2_access_token=${response.access_token}`,
         {
            method: 'GET',
            headers: {
               Accept: 'application/json',
            },
         },
      );
      const { elements = [] } = await userEmail.json();
      const email = elements[0]?.['handle~']?.emailAddress || '';
      onResolve(provider, { ...response, email });
   };
 `

**Comment by cuongdevjs** [comment]
ok, I think it can be a good solution. Feel free open a new issue if you have any problem.

**Comment by GuffyG** [comment]
> Maybe not the best way in onResolve you can get rest api this work for me!
> 
> ` onResolve={async ({ provider, data }) => { await handleResolve(provider, data); }} ` ![Screenshot 2566-08-11 at 18 07 00](https://user-images.githubusercontent.com/39942486/259990525-9e32d5d4-bebe-4f80-a3f5-0c4d816ffe81.png)


API call not working due to Cors policy.

**Comment by GuffyG** [comment]
> each scope needs to separate by a comma

I tried comma-separated scope too but again the issue is the same. 

Then use the this approach after getting the access token.

 const proxyUrl = "https://api.allorigins.win/get?url=";
    const linkedInApiUrl = `https://api.linkedin.com/v2/emailAddress?oauth2_access_token=${accessToken}&q=members&projection=(elements*(handle~))`;
    let emailAddressStr = "";
    try {
      const response = await fetch(
        proxyUrl + encodeURIComponent(linkedInApiUrl),
        {
          method: "GET",
        }
      );

      if (response.ok) {
        const data = await response.json();
        if (data.hasOwnProperty("contents")) {
          const content = JSON.parse(data["contents"]);
          emailAddressStr = content.elements[0]["handle~"]["emailAddress"];
        }
      }
    } catch (error) {
    }
    
    But here dependency is the proxy URL. Is it ok or may change near in future?
    
    Thanks

**Comment by cuongdevjs** [comment]
Seem email is hidden due to the policy of Linkedin. Send your access_token to backend so you can get everything you want.
