### ISSUE TITLE
login with instagram redirect is not working

### ISSUE THREAD

**Issue by abdullah75840** [cuongdevjs/reactjs-social-login#122]
when I login with instagram, the new tab is not closing which instagram login is open and not getting the provider and data..

**Comment by cuongdevjs** [comment]
please give me your code or reproduce an example.

**Comment by abdullah75840** [comment]
yeah sure I will
`  <LoginSocialInstagram
          client_id={process.env.REACT_APP_INSTAGRAM_APP_ID || ''}
          client_secret={process.env.REACT_APP_INSTAGRAM_APP_SECRET || ''}
          redirect_uri={window.location.href}
          onLoginStart={onLoginStart}
          onResolve={({ provider, data }) => {
            console.log(provider);
            console.log(data);
            setProvider(provider);
            setProfile(data);
          }}
          onReject={(err) => {
            console.log(err);
          }}
        >
          <SocialBtn>
            <span>
              <img src="/images/insta.png" alt="" />
              Connect With Instagram
            </span>
          </SocialBtn>
        </LoginSocialInstagram>`

**Comment by abdullah75840** [comment]
[screen-capture (23).webm](https://github.com/cuongdevjs/reactjs-social-login/assets/54703238/f7f5fb3b-1a39-4a69-8b64-a77e35b0b9cf)

**Comment by cuongdevjs** [comment]
seems you are set redirect_uri = appdev.renie.io, please make sure redirect_uri must equal your current url, in your case redirect_uri must be localhost:3000/login

**Comment by abdullah75840** [comment]
but it's not working on deployed link also..

**Comment by abdullah75840** [comment]
I have set redirect_uri like this redirect_uri={window.location.href}

**Comment by cuongdevjs** [comment]
I just accessed your deploy site, and i getting an error: `{"error_type": "OAuthException", "code": 400, "error_message": "Insufficient developer role"}`. seem you are setting your app incorrectly, this error doesn't belong to this library. Please double-check.

**Comment by cuongdevjs** [comment]
you can try to find solution here: https://stackoverflow.com/questions/58778302/instagram-display-api-insufficient-developer-role

**Comment by abdullah75840** [comment]
because we are now on testing mode that's why you getting this error..
