### ISSUE TITLE
Button customization and translation

### ISSUE THREAD

**Issue by chattago2002** [cuongdevjs/reactjs-social-login#123]
Hi.

I have 2 questions:
1) Is there a specific way to customize the buttons? At the moment I didn't found information in the repo documentation so I add my style to the button.
```
<GoogleLoginButton style={{ height: 'unset', fontSize: '15px', padding: '7px 15px' }} />
```
2) Is there a way to pass a translation string or the language ISO code to show a translated button?

Thank you

**Comment by cuongdevjs** [comment]
You can see [the example](https://github.com/cuongdevjs/reactjs-social-login/blob/master/example/src/App.tsx)

Basically, each component only has a div tag with no children inside so you can pass any HTML you want

**Comment by cuongdevjs** [comment]
feel free open a new one if you are still facing the same problem.
