### ISSUE TITLE
Google not fully reporting back some errors

### ISSUE THREAD

**Issue by franciscopaglia** [cuongdevjs/reactjs-social-login#127]
**Describe the bug**
Currently, when a non-Oauth error occurs in the Google flow (eg: The user closes the modal), no callback will be triggered by the Google component. Other components like Facebook and Apple do account for these cases in this same project.

**Expected behavior**
An error should be reported back to the client, at least to let the client know that the modal was closed.

**Additional context**
Already opened a PR to fix the issue #118, @cuongdevjs could you please review it?

**Comment by cuongdevjs** [comment]
Thank you so much. I appreciate it. I'll take a look at it this weekend.

**Comment by cuongdevjs** [comment]
The PR #118 merged and released. Thank you so much. I appreciate it

**Comment by franciscopaglia** [comment]
Thanks for your time @cuongdevjs, really appreciated!
