### ISSUE TITLE
Google login not working

### ISSUE THREAD

**Issue by Naveen-ecrubit** [cuongdevjs/reactjs-social-login#128]
The client id is always undefined(it is getting printed in console) for google login. Its was working till yesterday. But from today, I am not able to login with google since I am getting error in console as below attached image. Kindly provide a fix for this.

![Screenshot_1](https://github.com/cuongdevjs/reactjs-social-login/assets/121220651/710f2b30-850e-4d5c-98db-f9ab8e0a5f55)

**Comment by cuongdevjs** [comment]
please give me your code.

**Comment by cuongdevjs** [comment]
have you tried installing the latest version?

**Comment by Naveen-ecrubit** [comment]
> please give me your code.

@cuongdevjs This is my code.

<LoginSocialGoogle
                  client_id={"7134490-h****bnjkdj898989dh732uln.apps.googleusercontent.com"}
                  discoveryDocs="claims_supported"
                  scope="email profile"
                  access_type="offline"
                  onResolve={({ provider, data }) => {
                    console.log("data", data)
                    loginUser(data)
                  }}
                  onReject={({ error }) => {
                    notify();
                  }}
                >
                  <Button className='mx-2 my-2 py-2 addcartbtn d-flex align-items-center justify-content-center flex-row btn-sm'> <FcGoogle />&nbsp;Loginf</Button>
                </LoginSocialGoogle>

**Comment by Naveen-ecrubit** [comment]
> have you tried installing the latest version?

No I am currently using version 2.6.2 only. @cuongdevjs

**Comment by cuongdevjs** [comment]
Try to upgrade to 2.6.3 and try again.

**Comment by cuongdevjs** [comment]
sorry, but it is impossible right now. I'll catch this case in the future
