### ISSUE TITLE
Can't login on Google account the popup doesn't appears

### ISSUE THREAD

**Issue by rhuber-rbi** [cuongdevjs/reactjs-social-login#131]
**Describe the bug**
Hi guys I'm getting this error when I use idToken the popup to select the account doesn't appears

<img width="1034" alt="Captura de pantalla 2023-09-08 a la(s) 11 51 37" src="https://github.com/cuongdevjs/reactjs-social-login/assets/93785870/8fcf9736-9ba5-43c7-af20-627aa8a6e16c">

<LoginSocialGoogle
          client_id={googleServiceWebClientIds}
          fetch_basic_profile={true}
          ux_mode={'popup'}
          typeResponse="idToken"
          access_type={'offline'}
          discoveryDocs={'claims_supported'}
          onResolve={({ data }: IResolveParams) => {

          }}
          onReject={error => {
           
          }}
          onLoginStart={() =>
           
          }
        >
         {.....}
        </LoginSocialGoogle>

**Comment by cuongdevjs** [comment]
remove `access_type` prop

**Comment by rhuber-rbi** [comment]
I have already tested but the popup to login doesn't appear consistently, today in the morning I had the problem several times when I clicked on login and any popup appeared also any error on the console or network tab, if you click 3 or 4 times you will not get the google popup anymore

**Comment by cuongdevjs** [comment]
try the code below:
````
<LoginSocialGoogle
						client_id={
							""
						}
						onLoginStart={onLoginStart}
						redirect_uri={REDIRECT_URI}
						typeResponse="idToken"
						scope="openid profile email"
						ux_mode="popup"
						onResolve={({ provider, data }) => {
							
						}}
						onReject={(err) => {
							console.log(err);
						}}
					>
						<GoogleLoginButton />
					</LoginSocialGoogle>
````

**Comment by rhuber-rbi** [comment]
nope, same behavior, it works fine 2 or 3 times then it doesn't appears anymore, but the issue is just when we asking for idToken, with accessToken works fine every time

**Comment by rhuber-rbi** [comment]
When It starts failign I see this message on chrome console issues tab

<img width="668" alt="Captura de pantalla 2023-09-08 a la(s) 15 09 38" src="https://github.com/cuongdevjs/reactjs-social-login/assets/93785870/9df2f955-f521-47cb-a301-fddc4e834ee6">

**Comment by cuongdevjs** [comment]
have you tried my demo on [site](https://react-social-login.netlify.app/)? Does it work?

**Comment by cuongdevjs** [comment]
you need to call logout function before click to login button again.

**Comment by rhuber-rbi** [comment]
After the login success, the logout works fine, but the logout doesn't work if I didn't make a login as I'm closing the popup before making the login, I have solved by adding this to the onLoginStart


            
            window.google.accounts.id.prompt(notification => {
              if (notification.isNotDisplayed() || notification.isSkippedMoment()) {
                // clear g_state cookie if the pop-up has already been closed
                document.cookie = `g_state=;path=/;expires=Thu, 01 Jan 1970 00:00:01 GMT`;
              }
            });

**Comment by rhuber-rbi** [comment]
I'm not able to create a branch on your repo, if you want the fix this is the patch, you can test it if you want
[fix-g_state_google.patch](https://github.com/cuongdevjs/reactjs-social-login/files/12578494/fix-g_state_google.patch)

**Comment by cuongdevjs** [comment]
if you want to make any changes, please fork this project and make a Pull Request to i can review it. Thank you.
