### ISSUE TITLE
login with instagram is not working and also unable to implement twitter login

### ISSUE THREAD

**Issue by aniket0527** [cuongdevjs/reactjs-social-login#135]
login with instagram simply logged in the instagram and shows instagram ui and this happens in your online demo too.
also provide step by step process to get client id for twitter and instagram as video

**Comment by cuongdevjs** [comment]
please provide your code and the screenshot what happening?

**Comment by aniket0527** [comment]
![issue](https://github.com/cuongdevjs/reactjs-social-login/assets/42114420/25359f8d-cd6e-49fd-9f2b-4b10a3093ca8)

**Comment by aniket0527** [comment]
![issue](https://github.com/cuongdevjs/reactjs-social-login/assets/42114420/b96a22de-48a6-4199-8b97-f659437e53e9)

**Comment by aniket0527** [comment]
![issue](https://github.com/cuongdevjs/reactjs-social-login/assets/42114420/c9978451-9254-4764-a339-4952eb271b1f)

**Comment by cuongdevjs** [comment]
sorry, both are still working well on the site demo. On Twitter implementation, I think your configuration is wrong, please check again.

**Comment by aniket0527** [comment]
Login with instagram is still not working. Screenshot which I share is from your demo app only . And twitter login I implemented as yours, but still not working that why you also provide how to create app Id may be there is some mistake I do. Btw I follow some YouTube videos for it but still not working.

**Comment by cuongdevjs** [comment]
I am not sure why you can't use Instagram on site demo, but I have tried and it is still working. In Twitter, please make sure your app is public and accepted by Twitter.

![CleanShot 2023-10-01 at 06 34 51](https://github.com/cuongdevjs/reactjs-social-login/assets/33604446/9a65ea4d-5bef-4854-83a9-1853b844ceff)

**Comment by cuongdevjs** [comment]
- In Instagram method, I think your account restricts some scope so it can't work properly. Try with another account or use your own code with custom scope yourself.
- In Twitter method, as I said above, make sure your Twitter app is public and get client_id properly.

If you still face any trouble and you think it is a bug belong this library, don't hesitant to open a new issue.
