### ISSUE TITLE
Cannot find module 'react-social-login-buttons'

### ISSUE THREAD

**Issue by amin-da** [cuongdevjs/reactjs-social-login#138]
hi @cuongdevjs
when i  use :
import { GoogleLoginButton } from "react-social-login-buttons";
**typescript appear this error** :
'GoogleLoginButton' is declared but its value is never read.ts(6133)
Cannot find module 'react-social-login-buttons' or its corresponding type declarations.ts(2307) 

It seems necessary to add the types of this library in the following repository
https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by cuongdevjs** [comment]
sure, react-social-login-buttons is a different library with reactjs-social-login library. You need to install it before you can use it.
