### ISSUE TITLE
Linkedin Login Issue

### ISSUE THREAD

**Issue by Albinzr** [cuongdevjs/reactjs-social-login#14]
When click login in Linkedin i getting following error 

**Uncaught TypeError: Failed to resolve module specifier "@linkedin/jsecure". Relative references must start with either "/", "./", or "../".**

<img width="1378" alt="Screenshot 2021-09-11 at 4 24 43 PM" src="https://user-images.githubusercontent.com/7425577/132945487-93b76ab4-c127-4ed2-a6bc-d539af1341f8.png">

**Comment by cuongdevjs** [comment]
Can you produce an example on codesandbox?

**Comment by cuongdevjs** [comment]
I don't think the error belongs to this lib, can you produce your code so I can check for you?

**Comment by cuongdevjs** [comment]
If you still faced this issue on newest version 1.4.0, please tell me to know and re-open this issue

**Comment by texashedgeem** [comment]
I get the same problem
Failed to resolve module specifier "@linkedin/jsecure". Relative references must
