### ISSUE TITLE
Can't get the user's email on LoginSocialGoogle

### ISSUE THREAD

**Issue by Mudassar-dev** [cuongdevjs/reactjs-social-login#140]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cuongdevjs** [comment]
please give me your code. I've tried on the site demo and it still works

**Comment by Mudassar-dev** [comment]
@cuongdevjs please look into it

![Screenshot 2023-11-06 145352](https://github.com/cuongdevjs/reactjs-social-login/assets/102532833/8e0d48e8-3d97-4714-90d1-9d872dc73267)

**Comment by cuongdevjs** [comment]
please give me your code

**Comment by cuongdevjs** [comment]
or re-check the account's permission

**Comment by Mudassar-dev** [comment]
Code:
 <LoginSocialGoogle
                    client_id={process.env.REACT_APP_GOOGLE_CLIENT_ID || ""}
                    cookiePolicy={"single_host_origin"}
                    fields="name,email"
                    onResolve={GoogleAuth}

                    onReject={err => {
                        console.log(err);
                    }}
                >
                    <li><a><img src={SOCIAL_ICON.Login_Icon.google} /></a></li>
                </LoginSocialGoogle>

**Comment by Mudassar-dev** [comment]
```
Code:
  <LoginSocialGoogle
                    client_id={process.env.REACT_APP_GOOGLE_CLIENT_ID || ""}
                    cookiePolicy={"single_host_origin"}
                    fields="name,email"
                    onResolve={GoogleAuth}

                    onReject={err => {
                        console.log(err);
                    }}
                >
                    <li><a><img src={SOCIAL_ICON.Login_Icon.google} /></a></li>
                </LoginSocialGoogle>
```

**Comment by cuongdevjs** [comment]
have you tried to remove cookiePolicy and fields prop?

**Comment by quanndh** [comment]
<img width="773" alt="image" src="https://github.com/cuongdevjs/reactjs-social-login/assets/47892926/4ef251a9-34a9-4ba8-93a1-0c267dfe11ab">
Why im getting this instead of user information?
@cuongdevjs

**Comment by Mudassar-dev** [comment]
@quan

> <img alt="image" width="773" src="https://private-user-images.githubusercontent.com/47892926/284185383-4ef251a9-34a9-4ba8-93a1-0c267dfe11ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDQzODUsIm5iZiI6MTcwMTEwNDA4NSwicGF0aCI6Ii80Nzg5MjkyNi8yODQxODUzODMtNGVmMjUxYTktMzRhOS00YmE4LTkzYTEtMGMyNjdkZmUxMWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDE2NTQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiODA4MzRiNjJlNTU0YTE1ZjhmODFhM2JjMmM2NmM3NWVkNDYwMWMxNjdmNTY2ZTU4NTNkNmJlNTIyMzdiZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iLa5MFaoirxdhllgYm1cuIrWkjg_nzAKxnJmkZ_n1aw"> Why im getting this instead of user information? @cuongdevjs


Hi try this. it's work for me 

```
<LoginSocialGoogle
                    client_id={process.env.REACT_APP_GOOGLE_CLIENT_ID || ""}
                    typeResponse="idToken"
                    scope="openid profile email"
                    ux_mode="popup"

                    onResolve={({ provider, data }) => {
                        GoogleAuth({ provider, data });
                    }}

                    onReject={err => {
                        console.log(err);
                    }}
                />
```
