### ISSUE TITLE
Microsoft login issue

### ISSUE THREAD

**Issue by alexandr-reshodko** [cuongdevjs/reactjs-social-login#141]
Hi!
Thanks for this great plugin.

I have a problem with Microsoft authorization. When I try to login, it successfully gets the token but next request to "https://graph.microsoft.com/v1.0/me" fails with "403 Forbidden".
Here is my app permissions
<img width="765" alt="image" src="https://github.com/cuongdevjs/reactjs-social-login/assets/76474064/7422a315-581a-46bc-ba23-defd5616612d">

P.S. Login with google works without issues

**Comment by cuongdevjs** [comment]
Please give me your code. make sure you have passed proper scope to LoginMicrosoft

**Comment by alexandr-reshodko** [comment]
```
<LoginSocialMicrosoft
    client_id={MICROSOFT_ID || ''}
    redirect_uri={window.location.href}
    onResolve={({ provider, data }) => {
        console.log(provider, data)
    }}
    onReject={(err) => {
        console.log(err);
    }}
>
    <MicrosoftLoginButton />
</LoginSocialMicrosoft>
```

I'm using default scope

**Comment by cuongdevjs** [comment]
Have you checked the permission of your app? I mean MICROSOFT_ID. 403 permission code is out of the scope of this library.

**Comment by alexandr-reshodko** [comment]
I've set scope like this `scope={'openid profile User.Read email'}` and it worked.
Thanks
