### ISSUE TITLE
Server Error ReferenceError: window is not defined next js

### ISSUE THREAD

**Issue by tarangshah19** [cuongdevjs/reactjs-social-login#144]
**Describe the bug**
ReferenceError: window is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cuongdevjs** [comment]
this library only works on the client side. please use `ssr: false` when using.
