### ISSUE TITLE
Error:  window is not defined in nextjs 13

### ISSUE THREAD

**Issue by thainv92** [cuongdevjs/reactjs-social-login#148]
**Describe the bug**
when i run mode development in nextjs, i will display message error **'ReferenceError: window is not defined'**

**To Reproduce**
1. Source nextjs
2. npm run dev
3. view log with message: **ReferenceError: window is not defined**

**Expected behavior**
Not display message error

**Screenshots**
![image](https://github.com/cuongdevjs/reactjs-social-login/assets/133634759/1d57f774-232b-4239-98c5-bc28f3f87744)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome 119.0.6045.105
 - next: 13.5.6
 - reactjs-social-login: 2.6.3

**Comment by cuongdevjs** [comment]
duplicate #144
