### ISSUE TITLE
Error Could not find a declaration file

### ISSUE THREAD

**Issue by henobi** [cuongdevjs/reactjs-social-login#15]
Hi,

I'm getting the following error using the plugin:

```
Could not find a declaration file for module 'reactjs-social-login'. '/Users/hendrik/Repository/assetsquare/ui/node_modules/reactjs-social-login/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/reactjs-social-login` if it exists or add a new declaration (.d.ts) file containing `declare module 'reactjs-social-login';`  TS7016

    4 | import { Grid, Button, Divider, Typography } from '@material-ui/core';
    5 | import useAuth from '../../hooks/useAuth';
  > 6 | import { LoginSocialFacebook, LoginSocialGoogle } from 'reactjs-social-login';
      |                                                        ^
    7 | 
    8 | const AuthWithSocial: React.FC = () => {
    9 |   const { loginWithFacebook, loginWithGoogle } = useAuth();
```

I already deleted my node_modules folder and re-run yarn buit it dind't  help.

Do you have an idea?

**Comment by cuongdevjs** [comment]
you can use declare module on your d.ts file. try it out: 
````
declare module 'reactjs-social-login'
````

**Comment by cuongdevjs** [comment]
Please upgrade to version 1.4.0 to fix this issue. Sorry for my late reply.

**Comment by cuongdevjs** [comment]
Re-open if you still face this issue.

**Comment by adrienlamotte** [comment]
@cuongdevjs Hello ! I'm having the same issue, but with the 1.5.0. Could you check again please?
Thank you for your help!

**Comment by cuongdevjs** [comment]
> @cuongdevjs Hello ! I'm having the same issue, but with the 1.5.0. Could you check again please? Thank you for your help!

I'm checking now.

**Comment by cuongdevjs** [comment]
<img width="605" alt="Screen Shot 2021-09-30 at 02 53 36" src="https://user-images.githubusercontent.com/33604446/135340832-44991b14-75fd-47bc-ac94-50762aa9288d.png">

Please update to the newest version (1.5.2). I so sorry for this bug :)

**Comment by tudoiolena** [comment]
@cuongdevjs Hello ! I'm having the same issue, but with the 2.6.3
<img width="1199" alt="Screenshot 2024-02-27 at 16 13 20" src="https://github.com/cuongdevjs/reactjs-social-login/assets/153283223/2f87ae23-a863-4c46-943e-c0150b477ac6">
. Could you check again please? Thank you for your help!

**Comment by Med-Becha** [comment]
Hello ! I'm having the same issue, but with the 2.6.3 v Could you check again please?
Thank you for your help!
