### ISSUE TITLE
Apple Signin Modal Stuck

### ISSUE THREAD

**Issue by mrabro** [cuongdevjs/reactjs-social-login#153]
on a click, opens apple sign in modal.. when credentials are entered, confirms share email etc.. then final step to click continue.. it's stuck there.. not closing modal.

I am working in react js.

```
<LoginSocialApple
redirect_uri={`${CONSTANTS.SERVER_URL}auth/apple/callback`}
client_id="app.login.*****"
scope="name email"
onLogoutFailure={this.handleSocialLoginFailure}
onResolve={this.handleAppleSocialLogin}
onReject={(err) => {
  console.log(err);
}}
>
<SocialApple className="apple" />
</LoginSocialApple>
```

and when I am inspecting inside the modal, the first time when you click on the continue button which is last step.. in the console it shows the network call goes successfully and in return the valid response is returned like idToken etc... but the modal stays open and this information resides inside the modal.. but this response should be recieved in the handleAppleSocialLogin method.. and modal should disappear.

Can anyone tell me what's wrong here and what's wrong in this?

**Comment by cuongdevjs** [comment]
try to using redirect_uri = window.location.href instead of.
