### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by zuhaib10** [cuongdevjs/reactjs-social-login#156]
**Describe the bug**
I am using the package for social sign in 
using next 14 app router 
with "use client"

this is the first issue i am facing 

`Could not find a declaration file for module 'reactjs-social-login'. '/Users/zuhaibkhalifa/Development/mvp/araby_ai/araby_ai_landing/node_modules/reactjs-social-login/dist/reactjs-social-login.modern.js' implicitly has an 'any' type.`

the second issue 

its saying window is undefined
**Screenshots**

<img width="1241" alt="Screenshot 2023-11-30 at 11 23 50" src="https://github.com/cuongdevjs/reactjs-social-login/assets/135945110/5fb8980d-46d3-4c66-a62f-65985db84a7a">

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**Comment by cuongdevjs** [comment]
#7 #109 duplicated
