### ISSUE TITLE
getting window error while using google login in next js production

### ISSUE THREAD

**Issue by nrishav007** [cuongdevjs/reactjs-social-login#162]
**Describe the bug**
It is working fine in the development phase with a warning, when trying to deploy the project it gives an error.

**Screenshots**
https://github.com/cuongdevjs/reactjs-social-login/assets/76684171/d9205f3b-3c65-40d3-a4db-f4f13939f53d

**Desktop (please complete the following information):**
 - OS: Linux (Fedora)
 - Browser: Chrome
 - Version 120.0.6099.129

**Comment by cuongdevjs** [comment]
Duplicated: #7 #109 #156 #148
