### ISSUE TITLE
Github user email is null, despite user:email scope

### ISSUE THREAD

**Issue by epubreader** [cuongdevjs/reactjs-social-login#165]
https://stackoverflow.com/questions/35373995/github-user-email-is-null-despite-useremail-scope

please add following code when scope is user:email, thanks.
      const emailResponse = await fetch(`https://api.github.com/user/emails`);
      const emailData = await emailResponse.json();
      setUserEmail(emailData.find(email => email.primary).email);

**Comment by cuongdevjs** [comment]
if you aren't getting user's email, cuz you might not allow it, please follow this solution:
![CleanShot 2024-01-26 at 14 45 22](https://github.com/cuongdevjs/reactjs-social-login/assets/33604446/72d821bc-4451-4c1d-bea3-318aeeb12160)
