### ISSUE TITLE
Window is not defined error after importing LoginSocialGoogle

### ISSUE THREAD

**Issue by abdulla783** [cuongdevjs/reactjs-social-login#168]
**Describe the bug**
import { LoginSocialGoogle } from "reactjs-social-login"; After installing in my mac os when I imported i got the below error

**To Reproduce**

node_modules/reactjs-social-login/dist/reactjs-social-login.modern.js:1:410
the line number

**Screenshots**
<img width="1101" alt="image" src="https://github.com/cuongdevjs/reactjs-social-login/assets/56511576/75c8d5e7-bf2e-4b21-ae02-6b2f51f61e51">

Error in the terminal
<img width="1000" alt="image" src="https://github.com/cuongdevjs/reactjs-social-login/assets/56511576/db76dbfe-dde2-44ba-a4f0-7f4773a9c12f">

**Desktop (please complete the following information):**
 - OS: macos
 - Browser Chrome
 - Version  121.0.6167.160

**Comment by cuongdevjs** [comment]
duplicated: #7 #109 #156 #148 #144
