### ISSUE TITLE
Instagram login

### ISSUE THREAD

**Issue by Albinzr** [cuongdevjs/reactjs-social-login#17]
While login with Instagram it's only giving tokes as a response. It's not giving any profile-related info including user id.
is there any method to get the user info?

Edit

What I found out is there is an access token exchange API which you will need to pass the current token to get access token
https://api.instagram.com/oauth/access_token

**Comment by cuongdevjs** [comment]
I think you need to backend to do this.

**Comment by Albinzr** [comment]
@cuongdevjs Due to cross-origin request there is some issue, but if you use **JSONP** then that issue is solved.

**Comment by cuongdevjs** [comment]
I can do it and CORS isn't problem here. But in reality, you need to log in and save info user into your database. What's your specific case? I still don't understand why you need user's profile on client?

**Comment by Albinzr** [comment]
@cuongdevjs I'm my case I don't need to save any user data to the database, What I want is token and id (user id)
because both are used to make further API calls, because id is a part of URL itself

**Comment by cuongdevjs** [comment]
> @cuongdevjs I'm my case I don't need to save any user data to the database, What I want is token and id (user id)
> because both are used to make further API calls, because id is a part of URL itself

yes, I'll do it this week.

**Comment by Albinzr** [comment]
@cuongdevjs Thanks man.

**Comment by cuongdevjs** [comment]
I was just updated the user's profile on all providers. You can upgrade to the newest version 1.5.0.
Thanks. If you have any problem, let me know here.
