### ISSUE TITLE
Hi, I am facing the exact same problem. My API keys are correctly configured

### ISSUE THREAD

**Issue by bmorenobel** [cuongdevjs/reactjs-social-login#18]
Hi, I am facing the exact same problem. My API keys are correctly configured

_Originally posted by @bmorenobel in https://github.com/cuongdevjs/reactjs-social-login/issues/12#issuecomment-926500134_

**Comment by cuongdevjs** [comment]
can you reproduce an example to codesandbox.com?

**Comment by cuongdevjs** [comment]
or image about errors?

**Comment by cuongdevjs** [comment]
Hi. Are you still facing this problem?

**Comment by cuongdevjs** [comment]
try upgrade to the newest version 1.5.0. Feel free to reopen issue.

**Comment by bmorenobel** [comment]
Sorry I could not answer before. I will upgrade and let you know. Thanks
