### ISSUE TITLE
 <User provider={provider} profile={profile} onLogout={onLogoutSuccess} />

### ISSUE THREAD

**Issue by Rohini1206** [cuongdevjs/reactjs-social-login#180]
Cannot find name 'User'.ts(2304)

User component is not exposed

![image](https://github.com/user-attachments/assets/b464dc00-41f6-41d4-a413-8ff89b962712)

Even for import { LinkedInLoginButton } from 'react-social-login-buttons'

I had to separately installed 'react-social-login-buttons' which is not documented

**Comment by cuongdevjs** [comment]
You need to create your own User.tsx file.
