### ISSUE TITLE
Explain what is Linkedin AppSecret and AppId

### ISSUE THREAD

**Issue by Rohini1206** [cuongdevjs/reactjs-social-login#181]
![image](https://github.com/user-attachments/assets/8ec4a367-a40e-4891-af69-132a8adee260)

![image](https://github.com/user-attachments/assets/05278649-d9c7-4f45-9e84-423838f4d84f)

which one i should choose for this 
what is Linkedin AppSecret and AppId

**Comment by cuongdevjs** [comment]
appId is clientId
appSecret is Client Secret
