### ISSUE TITLE
Google - Add firstname/lastname fields

### ISSUE THREAD

**Issue by adrienlamotte** [cuongdevjs/reactjs-social-login#20]
Hello! 

Could you please add the firstname and lastname fields to the Google Auth datas?

https://github.com/cuongdevjs/reactjs-social-login/blob/42f2ec8f03524e1c2e38524278869c10ff5ee0f9/src/LoginSocialGoogle/index.tsx#L120

```
data.firstName = profile.getGivenName()
data.lastName = profile.getFamilyName()
```

Thank you!

**Comment by cuongdevjs** [comment]
Sorry but I'm busy right now, I can fix it on weekend, but I so appreciate it if you create a PRs

**Comment by adrienlamotte** [comment]
Sure, there you go: https://github.com/cuongdevjs/reactjs-social-login/pull/21

**Comment by cuongdevjs** [comment]
Thanks. Please checkout to the newest version. I merged your PR.
