### ISSUE TITLE
Facebook - add email

### ISSUE THREAD

**Issue by amasik** [cuongdevjs/reactjs-social-login#22]
Hello!

Could you please add the email to the Facebook Auth datas ?

Thank you!

**Comment by cuongdevjs** [comment]
sure, I'll do it today.

**Comment by cuongdevjs** [comment]
I using props fieldsProfile with a default value to get: https://github.com/cuongdevjs/reactjs-social-login/blob/f0bfa54c1098b8f3fed315674f646c10100bc9c4/src/LoginSocialFacebook/index.tsx#L60
In your case, you can change value of props: 
````
fieldsProfile = 'id,first_name,last_name,middle_name,name,name_format,picture,short_name,email,gender'
````
