### ISSUE TITLE
linkedin return CORS error

### ISSUE THREAD

**Issue by jeffersribeiro** [cuongdevjs/reactjs-social-login#24]
1 Access to fetch at 'https://cors.bridged.cc/https://www.linkedin.com/oauth/v2/accessToken' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Note: i also tried with https, but without success.
Thanks for helping guys

**Comment by cuongdevjs** [comment]
Can you make an example on codesandbox? I think it works on https.
What's the environment you using? clone or install from npm?

**Comment by cuongdevjs** [comment]
The newest version will be fixed this issue. You can check it out now. Thank you

**Comment by xuchen81** [comment]
google login has the same problem
