### ISSUE TITLE
the `'./User'` directory is completely missed from the repository

### ISSUE THREAD

**Issue by pdipietro** [cuongdevjs/reactjs-social-login#25]
**Describe the bug**
It looks like the `'./User'` directory is completely missed from the repository

Failed to compile.

./src/App.tsx
Module not found: Can't resolve './User' in '/ssd/reactjs-social-login/example/src'

**To Reproduce**
1. Just follow the instruction: when running `npm run start` it returns the error
Just looking at the code, there are two errors:

a) `import { User } from './User'` ts2307 impossible to find './User' module
b) the same for 
```
import {
  LoginSocialGoogle,
  LoginSocialAmazon,
  LoginSocialFacebook,
  LoginSocialGithub,
  LoginSocialInstagram,
  LoginSocialLinkedin,
  LoginSocialMicrosoft,
  LoginSocialPinterest,
  LoginSocialTwitter,
  IResolveParams,
  TypeCrossFunction
} from 'reactjs-social-login'
```
ts2307 impossible to find 'reactjs-social-login' module

**Additional context**
Running on Ubuntu 20.04

**Comment by cuongdevjs** [comment]
oh sorry about that, I miss that file. I'll fix it asap.

**Comment by cuongdevjs** [comment]
I just update the code newest and you can pull it now. Sorry about my late reply. Let me know if you facing any issues

**Comment by pdipietro** [comment]
Hi CuongDevjs, Thank you for having pathed the repo.

Now, I restarted from scratch, trying to follow you instructions step-by-step, and, when running `run npm start` into the `example` directory, I received the following error:

```
Failed to compile
./src/App.tsx
Module not found: Can't resolve 'reactjs-social-login' in '/test/reactjs-social-login/example/src'
```
Any help will be appreciated.

Paolo
