### ISSUE TITLE
ReferenceError: require is not defined in ES module scope, you can use import instead This file is being treated as an ES module because it has a '.js' file extension and 'app/node_modules/reactjs-social-login/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.

### ISSUE THREAD

**Issue by ks-rahul** [cuongdevjs/reactjs-social-login#28]
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and 'app/node_modules/reactjs-social-login/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.

i using in next js app with typescript

**Comment by cuongdevjs** [comment]
Please upgrade to the latest version. Thank you
