### ISSUE TITLE
The Twitter login doesn't run

### ISSUE THREAD

**Issue by pdipietro** [cuongdevjs/reactjs-social-login#32]
The twitter login doesn't run in your demo application on `https://react-social-login.netlify.app/`.
By the way, it doesn't run in my application too!

If you note, there is a `}` at the end of the button container. It is black and not easily visible. Maybe that could be a source of error.

**Comment by cuongdevjs** [comment]
Ok. Thank you. I gonna fix it soon

**Comment by cuongdevjs** [comment]
version 2.0.0 released. Please upgrade to the newest version. This issue will be fixed. Thank you.
