### ISSUE TITLE
After running build the LoginAuthentication starts to give {authResponse: null, status: 'unknown'} yet when running in development mode its running fine

### ISSUE THREAD

**Issue by DUMBALINYOLO** [cuongdevjs/reactjs-social-login#49]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cuongdevjs** [comment]
Hi. Can you describe clearly step by step your problem? Did you follow my instruction on README?
