### ISSUE TITLE
Can't click Facebook/Google/Amazon buttons again after cancelling signup

### ISSUE THREAD

**Issue by TdWa** [cuongdevjs/reactjs-social-login#52]
**Describe the bug**
After I close the popup window from Facebook/Google/Amazon to cancel, reclicking the button doesn't work untill I refresh the page. I don't have this issue with the other buttons from Instagram etc.

**To Reproduce**
1. Go to https://react-social-login.netlify.app/
2. Click on 'Log in with Facebook' (or Google or Amazon)
3. Click on 'OK'
4. Close the Facebook popup window/tab
5. Click on 'Log in with Facebook' (or Google or Amazon)
Error: nothing happens

**Expected behavior**
When clicking the 'Log in with Facebook/Google/Amazon' button the 2nd time in step 5 I expect the button to work as before.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome Version 102.0.5005.115 (Official Build) (x86_64)

**Comment by cuongdevjs** [comment]
ok, thank you because of your feedback. Let me check for you.

**Comment by cuongdevjs** [comment]
Hi. Please upgrade to the latest version. This issue is fixed. Thank you.

**Comment by TdWa** [comment]
Thanks for the quick fix!
