### ISSUE TITLE
Can't click Google button again after the LoginSocialGoogle component previously dismounted

### ISSUE THREAD

**Issue by TdWa** [cuongdevjs/reactjs-social-login#54]
**Describe the bug**
In my app after I login with LoginSocialGoogle I go to a different page without the LoginSocialGoogle component. Then when I logout and go back to login again the button doesn't work.

Looking at your source code I found that the reason is because after the LoginSocialGoogle dismounts and then mounts again, the SDK script is still in the DOM so [`if (checkIsExistsSDKScript())` ](https://github.com/cuongdevjs/reactjs-social-login/blob/f8eee2da54fa16dc4a5f8366ef78886604861b26/src/LoginSocialGoogle/index.tsx#L147) is true and `isSdkLoaded` is set to true, but `instance` is still null because it got reset when the component dismounted, so then this check [`if (instance) instance.requestAccessToken()`](https://github.com/cuongdevjs/reactjs-social-login/blob/f8eee2da54fa16dc4a5f8366ef78886604861b26/src/LoginSocialGoogle/index.tsx#L197) won't succeed.

I made a workaround to fix the issue in my app by removing the SDK script when the component dismounts in a useEffect cleanup function. That way when the component mounts again `checkIsExistsSDKScript()` will return false and the script and instance are set again.

```
useEffect(() => {
    return () => {
        document.getElementById(SCRIPT_ID)?.remove();
    };
}, []);
```
But maybe you could add a fix in your library instead?

**To Reproduce**
In your demo the issue doesn't happen because when you login the LoginSocialGoogle component doesn't actually dismount, it is only hidden with ``<div className={`App ${provider && profile ? 'hide' : ''}`}>``. So to reproduce the issue you should render LoginSocialGoogle conditionally so it dismounts after logging in`

After making that change
1. Login with the Google button
2. Logout
3. Click the Google button again

**Expected behavior**
After dismounting and remounting the LoginSocialGoogle component and clicking the Google login button a 2nd time `requestAccessToken` should be called again as before

**Comment by TdWa** [comment]
> Hi. Thank you for your feedback it really useful. But can you make a PR to fix this? I appreciate it if you can. because I am quite busy right now, but if you can't, I will fix this in the next few days. Regards.

Done 👍
I am not so familiar with the Google library so I'm not sure if there might be a better solution, but this does fix the issue at least.

**Comment by cuongdevjs** [comment]
ok, thank you very much. Not only Google but others too. I will fix them all and push it soon.

**Comment by cuongdevjs** [comment]
Hi. I've released a new version to fix this problem. Please upgrade to the latest version. Thank you for your report :)

**Comment by TdWa** [comment]
Hi, thanks for the quick update.

The issue is partly resolved but there are some cases where it still happens (I tried it with the Google button).

You placed the call to remove the Google script inside the resolve function, so IF the login succeeds there is no more issue.
But the issue can still happen if users don't login. For example if:

- users go to my login page -> LoginSocialGoogle component sets script and client instance
- then go to my home page without logging in -> LoginSocialGoogle unmounts but didn't remove the script because there was no resolve
- then go back to my login page -> LoginSocialGoogle still has the script so the client instance remains null

using the useEffect cleanup function does work for me in all cases

**Comment by cuongdevjs** [comment]
Thank you. I got you mean. I don't think about that :) Let me fix it now

**Comment by cuongdevjs** [comment]
Please upgrade to the latest version (2.5.1). Thank you for your report 💯

**Comment by TdWa** [comment]
Thanks! 👍

We actually found one more about (edge) case today where it could go wrong. The Google button also won't work if you already have another Google button mounted at the same time. And then the useEffect cleanup also won't help.

This is an edge case in our application.. we have a login page and also a login modal popup that can be openend from our header. I don't think many users will click both but if you could find a way to fix this that would be cool. Otherwise we can maybe find a workaround in our own application.

**Comment by TdWa** [comment]
If it would somehow be possible to get the Google client instance from an existing script then this trick to remove and recreate the script + client instance wouldn't be necessary

**Comment by cuongdevjs** [comment]
> If it would somehow be possible to get the Google client instance from an existing script then this trick to remove and recreate the script + client instance wouldn't be necessary.
> 
> Or maybe a check to recreate the script and client instance also if the script exists but the client instance is null
> 
> Like
> 
> ```
> useEffect(() => {
>     (!isSdkLoaded || !instance) && load()
>   }, [instance, isSdkLoaded])
> ```
> 
> and then inside `load` also check for `!instance` and probably if the script exists but not the instance, first remove the script before recreating it

Insert multiples SDK script isn't a solution. I think you can think about using Login Popover on your header to show LoginProvider
