### ISSUE TITLE
Can't prevent double request due to double click

### ISSUE THREAD

**Issue by TdWa** [cuongdevjs/reactjs-social-login#56]
**Describe the bug**
When I double click the social buttons it does 2 requests, the SDK popup reopens and onResolve is called twice etc.
I've tried setting isDisabled to true on the first click but that didn't help.

I believe there was logic to prevent this before, but it was removed here to fix another issue? https://github.com/cuongdevjs/reactjs-social-login/commit/f8eee2da54fa16dc4a5f8366ef78886604861b26

It would be great if some logic could be added again so the buttons can only be clicked again after the previous click was resolved/rejected (without recreating the previous issue where the button couldn't be reclicked if the login was cancelled by the user).

**To Reproduce**
It can be reproduced with the example demo if you remove the [alert in onLoginStart](https://github.com/cuongdevjs/reactjs-social-login/blob/0ba501fe61cfddd49b49f443b31c60d82be47ddb/example/src/App.tsx#L48) and then click for example the Facebook button multiple times

**Comment by cuongdevjs** [comment]
Because of some limitations, I only can add a check click on the Facebook component (version 2.5.2). But on other components, I can't detect whether users close the modal or not, so I think it's impossible
