### ISSUE TITLE
In Firefox and Safari users are logged in to Facebook despite cancelling the login

### ISSUE THREAD

**Issue by TdWa** [cuongdevjs/reactjs-social-login#57]
**Describe the bug**
When I tried the Facebook login in Firefox and Safari I got logged in after closing the login popup window

**To Reproduce**
1. Go to https://react-social-login.netlify.app/ in Firefox or Safari
2. Log in with the "Log in with Facebook" button
3. Go to facebook.com and log out there (I used a new tab)
4. Go back to the demo app tab and refresh the page
5. Click the "Log in with Facebook" button
6. Close the popup window
Now the login continues anyway

**Comment by cuongdevjs** [comment]
Thank you. I gonna fix it on weekend.

**Comment by cuongdevjs** [comment]
oh, I just look at this problem,  I think it is an option of Facebook, you can try to add this option to your Facebook component: `` auth_type="reauthenticate" ``
You can refer to know more at https://developers.facebook.com/docs/facebook-login/guides/advanced/re-authentication

**Comment by cuongdevjs** [comment]
Let me know if you have fixed this problem. Thank you

**Comment by TdWa** [comment]
Thanks for looking into it. Using this option does indeed take away the bug, but it should not be necessary to use this I think. I would prefer not to force my users to re-enter their password unnecessarily. It's just really odd that when you cancel the login by closing the popup at step 6 you get logged in instead.

**Comment by cuongdevjs** [comment]
Oh, it depends on your needs, once you are auth on FacebookOauth, cookies will be saved and after that, if you click FacebookOauth again, it won't show up popup and auth immediately based on cookies that were saved previously. So have some options for you to you can try change auth_type props (refer to  https://developers.facebook.com/docs/facebook-login/guides/advanced/re-authentication )

**Comment by TdWa** [comment]
Did you follow the steps I described above in Safari or Firefox?

The problem is that the popup does show up in step 5, but then when you close it you get logged in anyway.

**Comment by cuongdevjs** [comment]
Hi. I've implemented follow your steps, but it still works normally.
When I log out of Facebook on new tab, and back to react-social-login page, click LoginFacebook again, the popup asks user/pass still shows up.
Can you check again? Or can send me your recording about that.

**Comment by cuongdevjs** [comment]
https://user-images.githubusercontent.com/33604446/179869456-d9effd09-e545-4b58-b2ad-3ac333e9ff2d.mov

**Comment by TdWa** [comment]
Hi, thanks for checking again. I wish I had recorded it before because now I can't reproduce it anymore either!

So I think the issue is gone 👍

**Comment by cuongdevjs** [comment]
Ok. Don't hesitantly let me know if you have any questions :D thank you
