### ISSUE TITLE
Linkedin Popup Issue

### ISSUE THREAD

**Issue by teachingate** [cuongdevjs/reactjs-social-login#58]
When the LinkedIn popup opens up and the user logs in successfully, the redirect URL opens up in the same popup. How to force it to return back to the parent window?

**Comment by cuongdevjs** [comment]
hi, are you following my code on ReadME? Can you give me your code?

**Comment by teachingate** [comment]
@cuongdevjs Thanks for paying attention to this issue. Here is the code -

`<LoginSocialLinkedin
  client_id={process.env.REACT_APP_LINKEDIN_APP_ID || ''}
  client_secret={process.env.REACT_APP_LINKEDIN_APP_SECRET || ''}
  redirect_uri={`${window.location.origin}/linkedin`}
  onResolve={({ provider, data }: IResolveParams) => {
    console.log(provider);
    console.log('Linkedin data', data);
  }}
  onReject={(err) => {
    console.log('Linkedin err', err);
  }}
>
    <Button>Linkedin</Button>
</LoginSocialLinkedin>`

**Comment by cuongdevjs** [comment]
can you send me a record of your screen of your problem?

**Comment by teachingate** [comment]
The problem is, that it is not redirecting to the parent window. Instead, it is opening the redirect URL in the LinkedIn popup window.
![liLogin](https://user-images.githubusercontent.com/100257579/179471341-67ca41e2-f144-4de5-b05f-242e15f1ff84.png)

**Comment by teachingate** [comment]
The problem is, that it is not redirecting to the parent window. Instead, it is opening the redirect URL in the LinkedIn popup window.
![liLogin](https://user-images.githubusercontent.com/100257579/179473069-0f9a9367-7e5a-493f-be53-785afcb334e1.png)

**Comment by teachingate** [comment]
Already tried it, but for your sake, I've tried it one more time. Still the same result. It is opening the redirect_uri in the linkedin login popup window.

**Comment by teachingate** [comment]
This solution is not working for me. Please drop a message if you find anything.

**Comment by cuongdevjs** [comment]
I don't face this issue before. If can, let me take a look at your code so I can check it directly for you.

**Comment by cuongdevjs** [comment]
Let me know if you still need help

**Comment by fenil2502** [comment]
I am also struggling with this issue, when I login successfully the popup opening of redirect url how to close that window
