### ISSUE TITLE
Twitter API v2 / OAuth 2.0 Support

### ISSUE THREAD

**Issue by OskarEichler** [cuongdevjs/reactjs-social-login#60]
Great work on this repo @cuongdevjs ! Is there any chance to implement the new OAuth 2.0 Flow that was introduced with the Twitter API v2?

The new OAuth 2.0 Flow doesn't require to disclose the client secret, so it would actually be possible to use the gem in production.

See the documentation here for reference:
https://developer.twitter.com/en/docs/authentication/oauth-2-0/authorization-code

**Comment by cuongdevjs** [comment]
ok. that's great. I will research and implement it soon.

**Comment by OskarEichler** [comment]
Awesome thank you!

**Comment by OskarEichler** [comment]
@cuongdevjs It looks to me like Twitter might be blocking the tracking of window.open via its CORS policy?

**Comment by cuongdevjs** [comment]
I've tried on https://react-social-login.netlify.app/ and it still works.

**Comment by OskarEichler** [comment]
@cuongdevjs I meant for the v2 API flow with OAuth 2.0

**Comment by cuongdevjs** [comment]
no, it still works, I am trying to change it to v2 and I think it is possible.

**Comment by OskarEichler** [comment]
Okay awesome! I was trying to implement it and am having issues with the detecting the end of the auth flow when Twitter redirects and has the code in the URL. If you can get that callback to work would be awesome! 🙌🏼

**Comment by cuongdevjs** [comment]
Hi. Everything is ready to use. Please upgrade to the newest version (v2.5.2)
Thank you.

**Comment by OskarEichler** [comment]
Awesome, thank you @cuongdevjs 

I see it is definitely working on your demo site - however, for me it doesn't redirect from the callback (see screenshot below):
![Screenshot 2022-08-07 at 22 18 16](https://user-images.githubusercontent.com/62393985/183295185-7a5ec719-b888-4146-a3cb-60cb06a51182.jpg)

Code is pretty simple:

```
import React, { useCallback, useEffect, useState } from 'react'
import { ICON_NAMES } from '../../../utils/Constants';
import * as globalStyles from '../../../utils/GlobalStyles';
import ButtonView from '../../atoms/ButtonView';
import { LoginSocialTwitter } from 'reactjs-social-login';

const REDIRECT_URI = 'http://localhost:8000/callback'

export default function TwitterLoginButtonView(props) {
  const { 
    sourceObjectType,
    sourceObjectId,
    authGoogle,
    source,
    isBackstageAuthorized,
    buttonText="connect"
  } = props;

  const scope = 'tweet.read%20users.read%20offline.access';
  const state = 'twitter'

  const [provider, setProvider] = useState('');
  const [profile, setProfile] = useState('');

  return (
    <LoginSocialTwitter
      client_id={'SE10ME5MTTM4a3FwSURBdWVfTDU6MTpjaQ'}
      client_secret={''}
      redirect_uri={"http://localhost:8000/callback"}
      onResolve={({ provider, data }) => {
        console.log(provider, data)
      }}
      onReject={(err) => {
        console.log(err)
      }}
    >
      <ButtonView
        text={buttonText}
        customButtonBackgroundColor={source.buttonColor || source.iconColor}
        disabled={!!isBackstageAuthorized}
        rightIcon={!!isBackstageAuthorized ? { name: ICON_NAMES.CHECKMARK, color: globalStyles.colors.text3, size: 12, style: { paddingLeft: 6 } } : undefined}
      />
    </LoginSocialTwitter>
  );
}
```

Also it would be great if we can pass in `state` and `scope` so that we can customize them.

**Comment by cuongdevjs** [comment]
please make sure:
- redirect_uri must be the same as the URL where the Twitter Login component is located (example: you put TwitterLogin on URL localhost:3000/login, so redirect_uri must be localhost:3000/login too)
- the component TwitterLogin must exist (on DOM) when redirect_uri is returned (you shouldn't destroy or unmount the TwitterLogin component before login successfully)

**Comment by cuongdevjs** [comment]
> Also it would be great if we can pass in `state` and `scope` so that we can customize them.

Please upgrade to version 2.5.4, both props are available to use.

**Comment by OskarEichler** [comment]
Amazing, thanks for clarifying @cuongdevjs!

This is now working as expected, and also huge thanks for implementing the `state` and `scope` params so quickly!

Last question: Would it be possible to pass down another param to only execute onLogin without calling getAccessToken and getProfile. Essentially all that we need is the code that is coming back from the original authorization window, then we handle the rest server side. Will be great if you can make an option for that!

**Comment by cuongdevjs** [comment]
sure, it is possible. I think I will do that for all components.

**Comment by cuongdevjs** [comment]
can you create a new issue for that?

**Comment by OskarEichler** [comment]
Will do, thank you!
