### ISSUE TITLE
Make getAccessToken & getProfile optional

### ISSUE THREAD

**Issue by OskarEichler** [cuongdevjs/reactjs-social-login#61]
It would be great if it was possible to pass down a param to only execute onLogin without calling getAccessToken and getProfile. 

Essentially all that we need is the auth code that is coming back from the original authorization window, then we handle the rest server side, so no need to exchange the code and grab profile data. Will be great if you can make an option for that!

**Comment by cuongdevjs** [comment]
Thank you. I gonna do that soon.

**Comment by cuongdevjs** [comment]
This feature is complete, and I will release it soon

**Comment by OskarEichler** [comment]
Awesome thank you 🙏🏼

**Comment by cuongdevjs** [comment]
🔖 2.5.5 version has been published

**Comment by OskarEichler** [comment]
@cuongdevjs I saw that now the option you added was to make getProfile optional, but it still tries to exchange the code for an accessToken every time. It would be great if you can make that optional as well. All the we need is the code from the original authorization response, we then exchange the code for an authToken server side. We don't want to use any CORS bride, so prefer to handle it all server side.

**Comment by cuongdevjs** [comment]
oh, yes, you just need to pass props isOnlyGetToken to your component.

**Comment by OskarEichler** [comment]
@cuongdevjs Well but that then still tries to exchange the code for an auth_token? We only need the code, no need to send any request to exchange the code for the auth_token in the users frontend.

**Comment by cuongdevjs** [comment]
ok. What components are you mentioning?

**Comment by OskarEichler** [comment]
As far as I can tell, most of the components work the same:

1. User performs on-click, opens the authorization window and authorizes -> CODE
2. The Code is then being exchanged for an auth_token -> AUTH_TOKEN
3. The auth_token is then being used to fetch the profile of the user -> PROFILE

Before it was always doing all 3 steps. Now you made the new isOnlyGetToken parameter, which now is doing only step #1 and step #2. However, we only need step #1. All that we need is for example for the Twitter API to return us the CODE. We then handle the exchange ourselves server-side.

**Comment by cuongdevjs** [comment]
Ok. I got it. I will add one more prop to do only step #1.

**Comment by OskarEichler** [comment]
Awesome thank you!

**Comment by cuongdevjs** [comment]
I've completed it, and it will be released soon.

**Comment by OskarEichler** [comment]
Perfect thank you @cuongdevjs - please let me know when that has been released!

**Comment by cuongdevjs** [comment]
It has been released. please upgrade to 2.5.6 and then add prop `isOnlyGetCode` (read more on README.md)
