### ISSUE TITLE
idToken not response GoogleLogin

### ISSUE THREAD

**Issue by chipcop106** [cuongdevjs/reactjs-social-login#64]
I added "openid" attribute to the scope but idToken does not contain response data.

**Comment by cuongdevjs** [comment]
resolved when back the old version 2.0.1

**Comment by juanludlf** [comment]
Hi, is this feature working fine in recent versions?

**Comment by IvanCoronado** [comment]
I need `openId` but can't use `2.0.1` because require react 17 https://github.com/cuongdevjs/reactjs-social-login/blob/v.2.0.1/package.json#L31-L34 and we are using react 18

**Comment by cuongdevjs** [comment]
oh, yeah, this is an old mechanism and will be deprecated. So I've changed it to the new mechanism and i don't know why openId isn't included in it.
<img width="501" alt="Screen Shot 2022-10-05 at 15 03 56" src="https://user-images.githubusercontent.com/33604446/194010962-a4ea9586-5915-476a-b80a-ccd36887f353.png">

**Comment by cuongdevjs** [comment]
> I need `openId` but can't use `2.0.1` because require react 17 https://github.com/cuongdevjs/reactjs-social-login/blob/v.2.0.1/package.json#L31-L34 and we are using react 18.
> 
> Why did you remove support for `openId`? Is deprecated or something like that?

You can add an option `--force` after npm install

**Comment by juanludlf** [comment]
Hi @cuongdevjs , thank you for your response. Could you tell me where have you read that the OpenID protocol is deprecated?
The doc says that new library is built on the OpenID Connect protocol and provides OpenID Connect formatted ID Tokens.

![image](https://user-images.githubusercontent.com/6860752/194028591-5327afd8-67e3-49b4-88ab-f97389a87428.png)

**Comment by cuongdevjs** [comment]
I don't say openId will be deprecated but on the new method: Google Identity Services I don't see any docs about getting openId although I was put openId scope. you can take a look at: https://developers.google.com/identity/oauth2/web/guides/migration-to-gis

**Comment by cuongdevjs** [comment]
please follow #73
