### ISSUE TITLE
Receiving error when attempting to login via twitter

### ISSUE THREAD

**Issue by thomas-mathers** [cuongdevjs/reactjs-social-login#67]
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/6652765/187009117-a1cab224-1b78-461f-8d99-07aa849e6289.png">

After clicking the authorize app button in the popup for twitter login I see that a network request is made and I receive this error. It seems like the request to https://cors.bridged.cc is expecting some authorization header which isn't present. I dug through your code and noticed that there is some key that you are passing "PASS_CORS_KEY" but this key is not present in the package (obviously). Could you tell me how to get this key and allow us to pass our own version into LoginSocialTwitter?

**Comment by cuongdevjs** [comment]
Ok. Here is the guide you get the key: https://github.com/gridaco/base/issues/23
