### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by hdminh247** [cuongdevjs/reactjs-social-login#7]
I got error message `window is not defined` in nextjs, codes implemented

```
<LoginSocialGoogle
      client_id={props.appId}
      onResolve={({ data }) => {
        alert(JSON.stringify(data));
      }}
      onReject={(err) => alert(err)}
    >
      Test
    </LoginSocialGoogle>
```

**Comment by cuongdevjs** [comment]
you should try to config ssr by false on your component

**Comment by itxtoledo** [comment]
This solved for me:

Create a custom component to show all social button that you need:

`import React from "react";
import { LoginSocialFacebook } from "reactjs-social-login";

const SocialLogin: React.FC = () => {
  return (
    <div>
      <LoginSocialFacebook
        appId={process.env.FACEBOOK_APPID}
        onReject={(e) => console.log(e)}
        onResolve={(e) => console.log(e)}
      >
        Facebook
      </LoginSocialFacebook>
    </div>
  );
};

export default SocialLogin;
`

Then import into your login page or your desired page to have social buttons:

`import dynamic from "next/dynamic";

const SocialLogin = dynamic(() => import("../../components/Auth/SocialLogin"), {
  ssr: false,
});

.... 

<SocialLogin />

`

Docs: https://nextjs.org/docs/advanced-features/dynamic-import

**Comment by cuongdevjs** [comment]
please reopen if you still facing this problem.

**Comment by Ssinz7-Sotanext** [comment]
@cuongdevjs  Help me! Error still occurs after using dynamic
