### ISSUE TITLE
not getting user data on Twitter logging 

### ISSUE THREAD

**Issue by Deeptrentium** [cuongdevjs/reactjs-social-login#71]
**Describe the bug**

**To Reproduce**
1. Click on LoginSocialTwitter

**Expected behavior**
getting logging use information 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
Code Example

<LoginSocialTwitter
                      client_id={client_id}
                      client_secret={client_secret}
                      redirect_uri="https://localhost:3000/club-settings/social-account"
                      scope="tweet.read users.read follows.read+follows.write offline.access"
                      onResolve={({provider, data}: IResolveParams) => {
                        console.log('twitter', provider, data)
                      }}
                      onReject={(err: any) => {
                        console.log("err",err)
                      }}
                    >
                      <Button
                        title={buttonTitle}
                        classAddon=" c-button--icons mr-60"
                        icon={`c-icon${buttonIcon}`}
                      />
                    </LoginSocialTwitter>

after successful login and redirect URL call and getting this error 

{error: "invalid_request", error_description: "Value passed for the authorization code was invalid."}

API called post https://cors.bridged.cc/https://api.twitter.com/2/oauth2/token

parameters 
{
  code: 
  redirect_uri: 
  https://localhost:3000/club-settings/social-account
  client_id: 
  grant_type: authorization_code
  code_verifier: challenge
}

**Comment by cuongdevjs** [comment]
Twitter still works normally on https://react-social-login.netlify.app/
Please make sure you has been added your local domain to your app and redirect_uri should be window.location.href

**Comment by cuongdevjs** [comment]
you can read README to see sample code and more detail

**Comment by cuongdevjs** [comment]
follow #72
