### ISSUE TITLE
google not returning id_token

### ISSUE THREAD

**Issue by iscars** [cuongdevjs/reactjs-social-login#73]
I only see the **access_token** in the response. I have tried different options but still can't get **id_token** (JWT). Is it possible to get it from the client directly without a server?

**Comment by cuongdevjs** [comment]
#64

**Comment by cuongdevjs** [comment]
#73

**Comment by iscars** [comment]
I did not delve into this library and did not look at the api on which it is built, but I opened the Google site, made a button according to the documentation and received an id token https://developers.google.com/identity/gsi/web/guides/display-button #html

**Comment by cuongdevjs** [comment]
id token will be returned on version 2.6.1
