### ISSUE TITLE
Instagram page not found issue  

### ISSUE THREAD

**Issue by Deeptrentium** [cuongdevjs/reactjs-social-login#74]
**Describe the bug**

**To Reproduce**
1. Go to your online demo
2. Click on Instagram login
4. See the error page not Found ( if a user is not already login )

**Expected behavior**
need to open the login page 

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [ Chrome ]

**Additional context**
This issue is not getting generated before.

**Comment by cuongdevjs** [comment]
Hi. I am going to my demo page and saw it still works normally.

**Comment by cuongdevjs** [comment]
Please share your screenshot to clarify this problem.

**Comment by cuongdevjs** [comment]
Close the issue due to no more information. Please create a new issue if you still need help.
