### ISSUE TITLE
 id_token not returned in google login in latest version

### ISSUE THREAD

**Issue by BaraskarJyoti** [cuongdevjs/reactjs-social-login#76]
- In older version(V 1.5.2) of `reactjs-social-login`, `data` attribute from `IResolveParams` was returning `id_token` which is needed for the authentication.
- In latest version, this field is not returned but `access_token` is returned.
- Looking into google [docs](https://developers.google.com/identity/oauth2/web/guides/migration-to-gis#google_identity_services_credential), the `id_token` seems to be equivalent to `credential` field which is returned by google identity services 
- looks like issue is related https://github.com/cuongdevjs/reactjs-social-login/issues/64
- can we please have a look and check how we can return this `credential`

Thanks!

**Comment by cuongdevjs** [comment]
Thank you. I will research it.

**Comment by BaraskarJyoti** [comment]
@cuongdevjs do you have any updates :) ?

**Comment by cuongdevjs** [comment]
Oh, sorry, I have been quite busy recently. I am going to do it this weekend.

**Comment by cuongdevjs** [comment]
PR is welcome.

**Comment by BaraskarJyoti** [comment]
Just some inputs: looks like the id_token (credentials) is returned in the callback response of 
`google.accounts.id.initialize`
References:
https://developers.google.com/identity/gsi/web/reference/js-reference
https://stackoverflow.com/questions/73367034/google-identity-services-login-with-react

**Comment by cuongdevjs** [comment]
It has almost been done and will be released soon. Thank you so much.

**Comment by cuongdevjs** [comment]
#64 
#73

**Comment by cuongdevjs** [comment]
🔥 v2.6.1 has been released. Please upgrade to the newest version.

**Comment by BaraskarJyoti** [comment]
Thank you for having a look!
But with idToken, we are not able to open the google popup in a window like how it is a case currently for the access token. With id_token we are only able to use one tap modal.
The use case I am expecting is to be able to have a id_token with google opening the popup window.

Do you have any idea how we can achieve it?

**Comment by cuongdevjs** [comment]
yes, but if you want to achieve this, you need an endpoint on the server side to handle a POST request, like this: https://developers.google.com/identity/gsi/web/reference/js-reference#login_uri

**Comment by BaraskarJyoti** [comment]
It seems that on custom button we can not get `id_token` on client side as google has separated authentication and authorisation flows.

Could we please remove the console added in the latest version.
` console.log('🚀 ~ file: index.tsx ~ line 153 ~ response', response);`
` console.log(client);`

Thanks!

**Comment by cuongdevjs** [comment]
now you definitely can get idToken in latest version
