### ISSUE TITLE
Twitter login takes 2 attempts on Live demo

### ISSUE THREAD

**Issue by rem4ik4ever** [cuongdevjs/reactjs-social-login#79]
**Describe the bug**
Currently in live Demo and in local development, twitter login needs 2 tries before getting to work. 

**To Reproduce**
1. Go to demo
2. Click on Twitter login
3. Network tab shows 400
4. Try again
5. Works

**Expected behavior**
Twitter login should only need 1 try to login

**Screenshots**
See one failed attempt to get token
<img width="797" alt="image" src="https://user-images.githubusercontent.com/3874496/201209360-f80bcc27-2a4f-4c1b-a42b-42fee359b082.png">
<img width="791" alt="image" src="https://user-images.githubusercontent.com/3874496/201209446-92241443-f3ea-44d7-92c8-20bc911f18fa.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 107.0.5304.87

**Comment by cuongdevjs** [comment]
oh, it is very strange. I can't reproduce it even on the demo page.

**Comment by cuongdevjs** [comment]
![Screenshot 2022-11-11 at 06 37 47](https://user-images.githubusercontent.com/33604446/201228485-ebdbf725-8979-4698-833f-820d9c2e0d45.png)
 I've even tried 3 times, and it still works normally.
