### ISSUE TITLE
How to get authorization code instead of access token?

### ISSUE THREAD

**Issue by thesafaraliyev** [cuongdevjs/reactjs-social-login#80]
First of all, thank you for the great package :) 

In my setup, I have reactjs application on the front end side and nestjs on the back end.

Because of API, I would like to use an **authorization code** to get the user information on the back end side, but currently as far as I've tested for facebook and google the code is automatically used by the `onGetMe` function to get the user information. 

How can I prevent this function from being called and get the authorization code on the `onResolve` function to be able to send it to my API?

**Comment by cuongdevjs** [comment]
Hi. you only need to pass `isOnlyGetToken` to both, and now you will get the data without calling `onGetMe` function

**Comment by thesafaraliyev** [comment]
@cuongdevjs This returns a bearer token, I'm asking authorization code

**Comment by thatAwesomeKK** [comment]
> 

For Google provider typeResponse="idToken", does not give anything

**Comment by cuongdevjs** [comment]
please share your code

> > 
> 
> For Google provider typeResponse="idToken", does not give anything login Window is not even opening

Could you share your code?

**Comment by FYL99** [comment]
Hi, I have the same issue, here is my code:
`LoginSocialGoogle
          client_id={process.env.REACT_APP_G_CLIENT_ID}
          redirect_uri={window.location.href}
          onLoginStart={onLoginStart}
          scope="openid profile email"
          access_type="online"
          typeResponse="idToken"
          
          onResolve={({ provider, data }) => {
            console.log(provider, data);
            // Do the login
            doLoginWithGoogle(data, 'g');
          }}
          onReject={err => {
            console.log(err);
            onLoginEnd();
          }}
        >
          <GoogleLoginButton />
        </LoginSocialGoogle>`

**Comment by Ian-potter** [comment]
I also have the same problem

**Comment by FYL99** [comment]
Sorry, but your sample code is not working, you can not get the idToken, only the accessToken. If you add the typeResponse="idToken" parameter, the code is no longer working. Please advice on the correct procedure on getting the idToken.

**Comment by cuongdevjs** [comment]
ok, i will check it.

**Comment by cuongdevjs** [comment]
Since the old implement was deprecated and the new GSI mechanism of Google Oauth has removed a lot of functionality since I apply the new method for this library, so I might need time to research to adapt it. IdToken won't be possible right now.

**Comment by cubuspl42** [comment]
As I see it, since latest changes to Google Sign In ([Google Identity Services for Web](https://developers.google.com/identity/gsi/web/guides/overview)), there's no official way to create a custom styled Google Sign In button. But it would be great if someone else confirmed that.

**Comment by cuongdevjs** [comment]
At now, this library is fully compatible and supports the new GSI mechanism. Currently, you can get either id_token, access_token and refresh_token
1. To get id_token, you just need to pass prop: `typeResponse="idToken"`, and you will get id_token under name credentials (renamed by Google)
2. To get access_token, pass prop: `typeResponse="accessToken"`
3. To get refresh_token, you will need to a backend server, you can only get code on client-side, and then send it to the backend (pass prop: `access_type='offline'`)

Please upgrade to the newest version to see the changes. Thank you.

**Comment by elapshynov** [comment]
When trying to get Google id_token - no popup is showed.
Version `reactjs-social-login@v2.6.3`

```typescript
<LoginSocialGoogle
    isOnlyGetToken
    typeResponse="idToken"
    client_id={GOOGLE_API_CLIENT_ID}
    onResolve={...}
 >
    {children}
</LoginSocialGoogle>
```
