### ISSUE TITLE
If the Google modal is closed, it won't open again for a certain period of time.

### ISSUE THREAD

**Issue by abizden** [cuongdevjs/reactjs-social-login#82]
**Describe the bug**
If I click the close icon in Google modal and I want to login again, the modal does not open without clearing the Browser memory. These periods are also included in the google document. But at least the google button should have the information that I was signed in before and it should open when I click it. For example, you can take a look at Twitter.

**Comment by abizden** [comment]
At the same time, if I have more than one account, in order to switch between them, for example, it is necessary to switch to that account from chrome. In the popups of previous google versions, it was possible to login by typing different e-mail addresses. Is this no longer possible?

**Comment by etienne-bondot** [comment]
I had the same issue.
After digging, I detect that the `g_state` cookie was responsible of it. My workaround was to remove it on `onLoginStart` callback:

```typescript
const handleLoginStart = (provider: IProvider) => {
    return () => {
        if (provider === 'google') {
            removeCookie('g_state', { path: '/' })
        }
    }
}

...

<LoginSocialGoogle
    access_type="offline"
    client_id={GOOGLE_CLIENT_ID}
    discoveryDocs="claims_supported"
    isOnlyGetToken
    onLoginStart={handleLoginStart('google')}
    onReject={handleReject('google')}
    onResolve={handleLoginSuccess}
    redirect_uri={REDIRECT_URI}
    typeResponse="idToken"
>
    Login with Google
 </LoginSocialGoogle>
```

**Comment by cuongdevjs** [comment]
You need to use our onLogout function before re-login again.
