### ISSUE TITLE
disabled attribute is not available

### ISSUE THREAD

**Issue by zawmn** [cuongdevjs/reactjs-social-login#87]
**Is your feature request related to a problem? Please describe.**
I need to prevent user to click LoginSocialLinkedin button before some kind of Agreement checkbox.
So I try to use disabled=true attribute to make LoginSocialLinkedin disabled.
But I got this error :  Property 'disabled' does not exist on type 'IntrinsicAttributes & Props'
I also try put AppButton within LoginSocialLinkedin and make AppButton disabled.  The button show disabled, but it can still click and show linkedin login. 

**Describe the solution you'd like**
LoginSocial plugin should support disabled attribute similar to other control like AppButton.

**Comment by cuongdevjs** [comment]
oh, I have a solution for you. Wrap the component with a div and make it to be disabled by CSS `pointer-event: none`.
