### ISSUE TITLE
Client Id is logged in the console for the Google component 

### ISSUE THREAD

**Issue by ty-codes** [cuongdevjs/reactjs-social-login#89]
*Describe the bug**
After clicking the log in with Google button, an intermediate object is logged onto the console.
The object contains the client Id and I don't think that's safe. I don't know if it happens because it takes too long to even load in the first place or if it's for some other reason.

**To Reproduce**
1. Click on 'Log In with google' button
3. Open the console
4. Data is logged in line 1 of reactjs-social-login.modern.js

**Expected behavior**
No logging of sensitive information

**Desktop (please complete the following information):**
 - Chrome

**Comment by cuongdevjs** [comment]
Could you make a PR?
