### ISSUE TITLE
getting console log  

### ISSUE THREAD

**Issue by mohdhaider07** [cuongdevjs/reactjs-social-login#92]
**Describe the bug**
I getting console.log and I am not logging it and the data is client id

**To Reproduce**
It shows up automatically in console after setting up

**Expected behavior**
no console.log should show in development

**Screenshots**

![image](https://user-images.githubusercontent.com/86488954/212139056-f8d02be9-3e04-4fad-8be1-3785fa75ed49.png)

**Desktop (please complete the following information):**

**Additional context**
I think the problem is in index.tsx file line number 210 
![image](https://user-images.githubusercontent.com/86488954/212138783-29ab0e6b-db98-4a76-81c1-419e301671ae.png)

**Comment by mohdhaider07** [comment]
I want to work on it

**Comment by cuongdevjs** [comment]
Hi. Thank you for your feedback. I'll do it later because I'm quite busy right now. Could you make a PR for this?

**Comment by mohdhaider07** [comment]
Ok assign this issue to me

**Comment by mohdhaider07** [comment]
@cuongdevjs  can you please review PR #93

**Comment by mohdhaider07** [comment]
@cuongdevjs you have merged the pr but not updated the npm package yet. Can you please update it

**Comment by cuongdevjs** [comment]
Thank you. Now you can upgrade to the newest version 2.6.2

**Comment by mohdhaider07** [comment]
@cuongdevjs Now the issue is resolved
