### ISSUE TITLE
Unable to get Microsoft authentication up and running

### ISSUE THREAD

**Issue by Jaimish00** [cuongdevjs/reactjs-social-login#94]
Hello @cuongdevjs 

Thanks for this amazing all-in-one package for social auth. 
I am facing an issue with Microsoft integration, and I am trying to resolve that, I am not able to understand the redirect URI implementation. 

I see that you've used a separate tunnelbear endpoint as a redirect URI in demo code. but I am not able to grasp the correct implementation for this whole Microsoft auth flow. Microsoft documentation is one big mess to understand. 
Can you make this implementation a bit more clear to me? and help me with what should go as redirect URI endpoint and what to implement?

**Comment by cuongdevjs** [comment]
Ok. It is simple. A redirect URI is the location where the authorization server sends the user once the app has been successfully authorized and granted an authorization code or access token. In my Microsoft Integration, you should set redirect Uri = window.location.href, and make sure that component <MicrosoftSocialLogin /> is shown on the DOM tree on that location (window.location.href)

**Comment by Jaimish00** [comment]
Okay, but while I've already implemented the component for redirect URI, in that component, I am getting the authorization code of microsoft, but what shall I do in that redirect component? Shall I do a fetch call to `/token` endpoint for microsoft tenant?

And one another thing, I am not getting any response from the onResolve callback.

**Comment by cuongdevjs** [comment]
Could I take a look at your code?

**Comment by Jaimish00** [comment]
Here is what I've done till now using the LoginSocialMicrosoft component,

```javascript
<LoginSocialMicrosoft
	isOnlyGetToken
	client_id={MicrosoftClientId}
	redirect_uri={MicrosoftRedirectURI}
	onResolve={({ provider, data }: IResolveParams) => {
	          console.log(provider)
	          console.log(data)
	}}
	onReject={(err: any) => {
	       	  console.log(err)
	}}>
	Login with Microsoft
</LoginSocialMicrosoft>
```

And here is the temporary API call written in redirect component
```javascript
axiosInstance
  .post("https://login.microsoftonline.com/common/v2.0/oauth2/token", {
    client_id: import.meta.env.VITE_APP_GOOGLE_CLIENT_ID,
    code: code,
    client_secret: import.meta.env.VITE_APP_MICROSOFT_CLIENT_SECRET
  })
  .then(data => {
    console.log(data)
  })
  .catch(error => {
    console.error(error)
  })
```
In the API call, I am getting CORS issue even though I've added the URI to Azure portal
![image](https://user-images.githubusercontent.com/48212176/212876124-3ad791c5-2b97-4293-8ad6-f975e735b74b.png)

**Comment by cuongdevjs** [comment]
I am not sure why you need to make an API call to endpoint /oauth2/token. As you can see, this library almost does it all for you, you just need to provide the correct information like redirect URI, and client_id and you will get access_token. What do you need? please clarify for me.

**Comment by cuongdevjs** [comment]
Make sure you've read the README file, you can see my sample code

**Comment by Jaimish00** [comment]
I've provided all the information correctly as you can see from my implementation of `LoginSocialMicrosoft` component. But once I click on the `Continue with Microsoft` button, it is taking me to the redirect URI and then it is not doing anything. 
As you said, I've already looked into the sample code, and I am finding this piece of code as bit of mystery to me
![image](https://user-images.githubusercontent.com/48212176/212902016-2628adab-593b-47f5-8092-ee879874f8c4.png)

You've added a tunnelbear URI here, is it pointing to some server code? or is it a frontend URI, as mentioned below in the commented line?

**Comment by cuongdevjs** [comment]
oh, you can misunderstand RedirectURI. redirect URI is the address location where redirected once successfully authorized, as I said before, it should be window.location.href.

**Comment by cuongdevjs** [comment]
<img width="870" alt="Screenshot 2023-01-17 at 22 24 00" src="https://user-images.githubusercontent.com/33604446/212938802-e58f230b-9edd-4c14-8fe0-ef95f85fba2c.png">


In code on README, I've written some notes about REDIRECT_URI.

**Comment by Jaimish00** [comment]
Here I have mentioned redirect URI as the same
![image](https://user-images.githubusercontent.com/48212176/213082506-9e34b525-a5c8-4175-a122-b6d427c26c84.png)

But it is redirecting me to the home screen of my app along with the code as you can see. and it is just stopping there and I am not getting any console logs that I've provided in the `onResolve` function

**Comment by cuongdevjs** [comment]
seem the component which contains reactjs-social-login is destroyed before success. make sure MicrosoftLoginSocial exists on DOM. Imagine you put MicrosoftLoginSocial on a modal, and then you close the modal before successfully authorizing, so this library can't handle and give the result.
