### ISSUE TITLE
Perform authentication in the same window instead of a popup

### ISSUE THREAD

**Issue by mighty-phoenix** [cuongdevjs/reactjs-social-login#98]
Hey @anver @adrienlamotte @SebastiaanNijland @cuongdevjs !
I am using the GoogleSignIn flow, and when I click on the sign in button, it opens a pop up for auth.
Please guide me regarding how I can perform the auth in the same tab/window, keeping rest of the functionality exactly the same.
Quick response would be highly appreciated.
Thanks!

**Comment by cuongdevjs** [comment]
You can try passing ux_mode mode by `redirect` to the Google component.
More detail at: https://developers.google.com/identity/sign-in/web/reference

**Comment by bhavesh2510** [comment]
hey @cuongdevjs @mighty-phoenix can you please share sample code for this? i'm trying to acheive same thing
need to open google/microsoft in same tab, here is what i tried but didn't worked,
using  "reactjs-social-login": "^2.6.3",

<LoginSocialGoogle
        isOnlyGetToken
        client_id={environment.googleAppId}
        onResolve={handleSignInGoogle}
        onReject={(err) => {
          //console.log(err);
        }}
        ux_mode={'redirect'}
        redirect_uri={window.location.href}
      > 

also when it opens in next tab, getting this error in console
**Cross-Origin-Opener-Policy policy would block the window.closed call.**
