### ISSUE TITLE
Redirection Not Working

### ISSUE THREAD

**Issue by amansinghcb** [cuongdevjs/reactjs-social-login#99]
Hi Team,

I am trying to signin/signup via Google and Microsoft. But, the redirection seems to be not working.
                          <LoginSocialGoogle
                            client_id={'***********************************************************' || ""}
                            onLoginStart={onLoginStart}
                            redirect_uri={"https://www.google.com"}
                            scope="openid profile email"
                            discoveryDocs="claims_supported"
                            access_type="online"
                            onResolve={({ provider, data }: IResolveParams) => {
                              console.log('134::', provider, data);
                              setProvider(provider)
                              setProfile(data)
                            }}
                            onReject={err => {
                              console.log(err)
                            }}
                          >
                            <Image path={"google-icon"} />
                          </LoginSocialGoogle>

**Comment by cuongdevjs** [comment]
Please follow our code sample on Readme. redirect_uri must be the same as the URL where put your Login component. It should be window.location.href

**Comment by cuongdevjs** [comment]
Please open a new issue if you still face trouble.
